version: '3.8'

networks:
  kong-net:
   name: kong-net
   driver: bridge
   ipam:
     config:
       - subnet: 172.1.1.0/24

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 3s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - kong-net
      
  web:
    image: alexolirib/cadastro:latest
    ports:
      - 8080:8080
    depends_on: 
      - postgres-db
    networks: 
      - kong-net
