version: '3.8'

networks:
  kong-net:
   name: kong-net
   driver: bridge
   ipam:
     config:
       - subnet: 172.1.1.0/24

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 3s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - kong-net

  kong-migration:
    container_name: kong-migration
    image: kong:2.1.4-alpine
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
    links:
      - postgres-db
    depends_on:
      - postgres-db
    
  kong:
    container_name: kong
    image: kong:2.1.4-alpine
    restart: unless-stopped
    networks:
      kong-net:
        ipv4_address: 172.1.1.40
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DB_UPDATE_FREQUENCY: 1m
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    depends_on:
      - kong-migration
    ports:
      - "8001:8001"
      - "8444:8444"
      - "8000:8000"
      - "8443:8443"
    
  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://kong:password@postgres-db:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    links:
      - postgres-db
    depends_on:
      - postgres-db

  konga:
    container_name: konga
    image: pantsel/konga:0.14.9
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: postgres-db
      DB_USER: kong
      DB_PASSWORD: password
      DB_DATABASE: konga_db
      # any string will OK for token
      TOKEN_SECRET: iu7YDcPLiZkozQXzZ9kka3Ee1Vid5ZgQ
      NODE_ENV: development
    depends_on:
      - konga-prepare
    ports:
      - "1338:1337"
      
  categoria:
    image: alexolirib/cadastro:latest
    depends_on: 
      - konga
    networks:
      kong-net: 
        ipv4_address: 172.1.1.11

      
  fornecedor:
    image: alexolirib/cadastro:latest
    depends_on: 
      - konga
    networks: 
      kong-net:
        ipv4_address: 172.1.1.12
      
  produto:
    image: alexolirib/cadastro:latest
    depends_on: 
      - konga
    networks: 
      kong-net:
        ipv4_address: 172.1.1.13
  
  swagger:
    image: alexolirib/cadastro:latest
    depends_on: 
      - konga
    networks: 
      kong-net:
        ipv4_address: 172.1.1.14
  